name: ViralLoopYT Daily Job

on:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST
    - cron: '30 9 * * *'    # 03:00 PM IST
    - cron: '0 16 * * *'   # 09:00 PM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ffmpeg & emoji font
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-noto-color-emoji

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run ViralLoopYT
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_TOKEN: ${{ secrets.YT_TOKEN }}
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: python ViralLoopYT.py
